.TH "btrfs-sxbackup-info" "1" "0.5.9" "Marco Schindler" ""
.SH "NAME"
.LP 
btrfs\-sxbackup\-info \- Show backup job info
.SH "SYNOPSIS"
.LP 
\fBbtrfs\-sxbackup info\fR [\-h] <subvolume> [<subvolume> ...]
.SH "DESCRIPTION"
.LP 
Show information about a \fBbtrfs\-sxbackup\fR job.
.SH "OPTIONS"
.LP 
.TP 
\fB<subvolume>\fR
backup job source or destination subvolume. local path or SSH url
.TP 
\fB\-h\fR, \fB\-\-help\fR
show help message and exit
.SH "SEE ALSO"
.LP 
btrfs\-sxbackup(1)
