.TH "btrfs-sxbackup-destroy" "1" "0.5.9" "Marco Schindler" ""
.SH "NAME"
.LP 
btrfs\-sxbackup\-destroy \- Destroy a backup job
.SH "SYNOPSIS"
.LP 
\fBbtrfs\-sxbackup destroy\fR [\-h] [\-\-purge] <subvolume> [<subvolume> ...]
.SH "DESCRIPTION"
.LP 
Destroy a \fBbtrfs\-sxbackup\fR job.
.SH "OPTIONS"
.LP 
.TP 
\fB<subvolume>\fR
backup job source or destination subvolume. local path or SSH url
.TP 
\fB\-h\fR, \fB\-\-help\fR
show help message and exit
\fB\-\-purge\fR
removes all backup snapshots from source and destination
.SH "SEE ALSO"
.LP 
btrfs\-sxbackup(1)
