__version__ = '0.4.1'
__author__ = 'Marco Schindler, Bernd Michael Helm'
__email__ = 'masc@disappear.de'
__maintainer__ = 'masc@disappear.de'
__license__ = 'GPL'
__copyright__ = 'Copyright 2014, Marco Schindler'
